---
title: "ISOM5610 Project"
author: "Team 1"
date: "14 December 2018"
output: pdf_document
---

```{r}
setwd("~/MSBA/ISOM5610/final")
claim <- read.table("Claim.csv", sep = ",", header = TRUE)
str(claim)
claim <- claim[-1]
```

# Descriptive Analysis

```{r}
summary(claim)
sum(is.na(claim)) # check missing value

summary(claim$Power)
summary(claim$Region)
```

```{r}
## this chunk calculate average values in different categories
avg_power <- data.frame(sapply(split(claim$Claim,claim$Power),mean))
# colnames(avg_power) <- 'avg'
# avg_power$Power <- rownames(avg_power)
avg_brand <- sapply(split(claim$Claim,claim$Brand),mean)
avg_region <- sapply(split(claim$Claim,claim$Region),mean)
```

There is no missing value. Claim: binary. Power: 12 categories. Brand:7 categories. Gas: binary. Region: 10 regions.

```{r}
library(ggplot2)
library(RColorBrewer)


ds1 <- ggplot(claim, aes(x=Exposure)) + 
    geom_density(aes(fill=factor(Claim)),alpha=0.5) +
    labs(title="Density of Claims by Exposure", 
       y="Density of Claims", 
       x="Exposure (Years)") + 
    scale_fill_manual(name = "Claim",
                      values = c(brewer.pal(7, "Reds")[5], brewer.pal(7, "Blues")[5]),
                      labels = c("Claim=0", "Claim=1"))
plot(ds1)


bar1 <- ggplot() + geom_bar(data=claim, aes(x=Power,fill=factor(Claim)))+
   labs(title="Distribution of Claims among different Power Types", y="Count by Power of Car", x="Power of car")+
scale_fill_manual(name = "Claim",values = c(brewer.pal(7, "Reds")[4],brewer.pal(7, "Blues")[5]),
                    labels = c("Claim=0", "Claim=1"))

plot(bar1)


ds2 <- ggplot(claim, aes(x=CarAge)) + 
  geom_density(aes(fill=factor(Claim)),alpha=0.5)+
  labs(title="Density of Claims by Car Age", y="Density of Claims", x="Car Age")+
  scale_fill_manual(name = "Claim",values = c(brewer.pal(7, "Reds")[5],brewer.pal(7, "Blues")[5]),
                    labels = c("Claim=0", "Claim=1"))
plot(ds2)


ds3 <- ggplot(claim, aes(x=DriverAge)) + 
  geom_density(aes(fill=factor(Claim)),alpha=0.5)+
  labs(title="Density of Claims by Driver Age", y="Density of Claims", x="Driver Age")+
  scale_fill_manual(name = "Claim",values = c(brewer.pal(7, "Reds")[5],brewer.pal(7, "Blues")[5]),
                    labels = c("Claim=0", "Claim=1"))
plot(ds3)


bar2 <- ggplot(claim, aes(x = Brand)) + geom_bar(aes(fill=factor(Claim)))+
   labs(title="Distribution of Claims among different Brands", y="Count by Brands", x="Brand")+
scale_fill_manual(name = "Claim",values = c(brewer.pal(7, "Reds")[4],brewer.pal(7, "Blues")[5]),
                    labels = c("Claim=0", "Claim=1"))

plot(bar2)

bar3 <- ggplot(claim, aes(x = Gas)) + geom_bar(aes(fill=factor(Claim)))+
   labs(title="Distribution of Claims among different Gas Types", y="Count by Gas Types", x="Gas Type")+
scale_fill_manual(name = "Claim",values = c(brewer.pal(7, "Reds")[4],brewer.pal(7, "Blues")[5]),
                    labels = c("Claim=0", "Claim=1"))

plot(bar3)

bar4 <- ggplot(claim, aes(x = Region)) + geom_bar(aes(fill=factor(Claim)))+
   labs(title="Distribution of Claims among different Regions", y="Count by Regions", x="Region")+
scale_fill_manual(name = "Claim",values = c(brewer.pal(7, "Reds")[4],brewer.pal(7, "Blues")[5]),
                    labels = c("Claim=0", "Claim=1"))

plot(bar4)

ds4 <- ggplot(claim, aes(x=Density)) + 
  geom_density(aes(fill=factor(Claim)),alpha=0.5)+
  labs(title="Density of Claims by Inhabitants Density", y="Density of Claims", x="Inhabitants Density (number of inhabitants per square km)")+
  scale_fill_manual(name = "Claim",values = c(brewer.pal(7, "Reds")[5],brewer.pal(7, "Blues")[5]),
                    labels = c("Claim=0", "Claim=1"))
plot(ds4)


```


```{r}
# geographical plot of claim %

library(dplyr)
claim_by_region <- tapply(claim$Claim, claim$Region, sum)
count_by_region <- summary(claim$Region)
regionID <- names(count_by_region)
regionIdx <- sub('.', '', regionID)

Sys.setlocale('LC_ALL','French')
library(readxl)
url1<-'https://insee.fr/fr/statistiques/fichier/1893198/estim-pop-dep-sexe-gca-1975-2018.xls '
tempdb <- tempfile()
download.file(url1, tempdb, mode="wb")
raw_db <- as.data.frame(read_excel(path = tempdb, range="2018!A6:B101", col_names=FALSE))
names(raw_db) <- c("RIdx", "RName")

region_table <- data.frame(regionID=regionID,
                        regionName=raw_db$RName[match(regionIdx, raw_db$RIdx)],
                        regionCount=count_by_region,
                        regionClaim=claim_by_region,
                        regionClaimPct=claim_by_region/count_by_region*100
                        )

library(maps)
france_map <- map_data("france")
claim_map <- merge(france_map, region_table, by.x = "region", by.y = "regionName", all.x = TRUE)
claim_map <- arrange(claim_map, group, order)
ggplot(claim_map, aes(x = long, y = lat, group = group, fill = regionClaimPct)) + 
    geom_polygon(colour = "white") +
    labs(title="Claim Rate (%) by Region", fill = "Claim Rate\n(%)") +
    scale_fill_viridis_c() +
    theme_void()
```

# Data Partition

```{r}
## there are 412,412 observatoins. Ramdomly partition ~80% and ~20% of the data into training and testing set

library(caTools)
set.seed(1111)
spl <- sample.split(claim$Claim, SplitRatio= 0.8)
claim_train <- subset(claim, spl==TRUE)
claim_test <- subset(claim, spl==FALSE)
```


# Fit the Model

## The Full Model

```{r}
fit.full <- glm(Claim~.,family=binomial,data = claim_train)  ## this one with default link func
summary(fit.full)
```

## Stepwise Selection

```{r}
fit.step <- step(fit.full)
summary(fit.step)
# the stepwise result suggests all 8 predictors are useful. We use fit.full as the base model going forward.
rm(fit.step)
```

## Interaction terms

```{r}
## check inter-correlation between non-categorical variables
claim1<-claim[c(2,4,5,9)]
library(corrplot)
corrplot.mixed(cor(claim1), upper = "ellipse", lower.col = "black")
# the correlation between non-categorical predictors are very weak, therefore chance of multicollinearity problem is slim

## vif
library(car)
vif(fit.full)
# all <10
```

```{r}
## Consider the interaction between the categorical variables

# check relationship between categorical variables
attach(claim_train)
r1 <- ggplot() +
  aes(x = Brand, color = Power, group = Power, y = Claim) +
  stat_summary(fun.y = mean, geom = "point") +
  stat_summary(fun.y = mean, geom = "line") + ggtitle('Brand:Power')+
  theme(axis.text.x = element_text(angle = 20, hjust = 1,size=8))


r2 <- ggplot() +
  aes(x = Brand, color = Gas, group = Gas, y = Claim) +
  stat_summary(fun.y = mean, geom = "point") +
  stat_summary(fun.y = mean, geom = "line") + ggtitle('Brand:Gas')+
  theme(axis.text.x = element_text(angle = 20, hjust = 1,size=8))


r3 <- ggplot() +
  aes(x = Brand, color = Region, group = Region, y = Claim) +
  stat_summary(fun.y = mean, geom = "point") +
  stat_summary(fun.y = mean, geom = "line") + ggtitle('Brand:Region')+
  theme(axis.text.x = element_text(angle = 20, hjust = 1,size=8))


r4 <- ggplot() +
  aes(x = Region, color = Gas, group = Gas, y = Claim) +
  stat_summary(fun.y = mean, geom = "point") +
  stat_summary(fun.y = mean, geom = "line") + ggtitle('Region:Gas')


r5 <- ggplot() +
  aes(x = Region, color = Power, group = Power, y = Claim) +
  stat_summary(fun.y = mean, geom = "point") +
  stat_summary(fun.y = mean, geom = "line") + ggtitle('Region:Power')


r6 <- ggplot() +
  aes(x = Power, color = Gas, group = Gas, y = Claim) +
  stat_summary(fun.y = mean, geom = "point") +
  stat_summary(fun.y = mean, geom = "line") + ggtitle('Power:Gas')

plot(r1)
plot(r2)
plot(r3)
plot(r4)
plot(r5)
plot(r6)
# library(gridExtra)
# grid.arrange(r1, r2, r3, r4, r5, r6, nrow = 3, ncol=2)

# From the interaction plots, we can find at least minor interaction effects for all 6 pairs (non-parallel crossed lines). Especially, we suspect there may be significant interactions between the follwoing pairs:
# (1)Brand:Power
# (2)Brand:Region
# (3)Region:Power
# (4)Power:Gas
```

```{r}
# For safe play, we further verify the significance of them by using LR test
library(lmtest)

fit.int1 <- update(fit.full,.~.+Power:Gas)
lrtest(fit.int1,fit.full)
# interaction bewtween Power:Gas is significant, we need to add this interaction item

fit.int2 <- update(fit.int1,.~.+Region:Gas)
lrtest(fit.int1,fit.int2)
# insignificant
rm(fit.int2)

fit.int3 <- update(fit.int1,.~.+Region:Power)
lrtest(fit.int1,fit.int3)
# Significant
rm(fit.int3)

fit.int4 <- update(fit.int1,.~.+Brand:Power)
lrtest(fit.int1,fit.int4)
# Significant
rm(fit.int4)

fit.int5 <- update(fit.int1,.~.+Brand:Region)
lrtest(fit.int1,fit.int5)
# Significant
rm(fit.int4)

fit.int6 <- update(fit.int1,.~.+Brand:Gas)
lrtest(fit.int1,fit.int6)
# insignificant
rm(fit.int6)

## put all significant items together

fit.int7 <- update(fit.int1,.~.+Region:Power +Brand:Power +Brand:Region)
```
brand and region should be recategorized, the other 6 predictors should be significant.

# Deviance Goodness of Fit Test

```{r}
1-pchisq(fit.int7$deviance,fit.int7$df.residual)
# p-value~1, i.e. it is a good fit model 
```

# Esimtated Probabilities 

```{r}
prob <- predict(fit.int7, newdata=claim_test, type = 'response')
table(claim_test$Claim, prob > 0.05)

library(InformationValue)
plotROC(claim_test$Claim,prob)

#Double density plot
p <- predict(fit.int7,type='response')
temp_train <- cbind(claim_train,p)
p <- prob
temp_test <- cbind(claim_test,p)
ggplot(temp_train, aes(p, color = as.factor(Claim))) + 
  geom_density(size = 1) +
  ggtitle("Training Set's estimated probabilities") 

#Confusion Matrix plot
source("~/MSBA/ISOM5610/Lect5/unbalanced_function.R")

cm_info <- ConfusionMatrixInfo( data = temp_test, predict = "p", actual = "Claim", cutoff = 0.05 )
cm_info$plot

#Optimal cutoff by considering cost
cost_fp <- 10
cost_fn <- 20
roc_info <- ROCInfo( data = cm_info$data, predict = "predict", 
                     actual = "actual", cost.fp = cost_fp, cost.fn = cost_fn )
grid.draw(roc_info$plot)

#error measure based on new cutoff
detach('package:caret')
sensitivity(test_set$default,prob,threshold = roc_info$cutoff)
specificity(test_set$default,prob,threshold = roc_info$cutoff)
confusionMatrix(test_set$default,prob,threshold = roc_info$cutoff)
misClassError(test_set$default,prob,threshold = roc_info$cutoff)
```

